name: pie-net
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.7
  - pip=20.3
  - pytorch==1.7.1
  - torchvision==0.8.2
  - torchaudio==0.7.2
  - cudatoolkit=11.0
  - pip:
      - imageio
      - tqdm
      - opencv-python
